source 'https://rubygems.org'

gem 'rails', '4.2.11'

# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.3.6' 
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'minitest', '~> 5.10.3' 

# Pin versions for compatibility with Ruby 2.1.0
gem 'execjs', '~> 2.7.0' 
gem 'nokogiri', '~> 1.9'
gem 'loofah', '~>2.19.1'

# For performance testing
gem 'rails-perftest', '0.0.6'  
gem 'ruby-prof', '0.15.9'   

gem 'analytical', :path => '../..'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

